# Generated by Django 3.2 on 2021-04-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodle',
            name='email',
        ),
    ]
